### ISSUE TITLE
你好请问selector里面的 color怎么换颜色呢

### ISSUE THREAD

**Issue by Wen-Guoguo** [arvinljw/ChangeSkinHelper#3]
切换之后selector颜色无法改变

**Comment by arvinljw** [comment]
selector的情况可以当作一个drawable，在不同模式下就需要配置不同的资源，例如bg_item这样一个selector，就需要添加bg_item_dark和bg_item_light两个一样的selector，内部的颜色也得换成对应模式下的，只有这样才能实现。

**Comment by arvinljw** [comment]
上传了selector换肤的例子了。
